/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./pages/__root"
import { Route as MainLayoutRouteImport } from "./pages/_main-layout"
import { Route as LayoutRouteImport } from "./pages/_layout"
import { Route as AuthRouteImport } from "./pages/_auth"
import { Route as MainLayoutIndexRouteImport } from "./pages/_main-layout/index"
import { Route as AuthLoginRouteImport } from "./pages/_auth/login"
import { Route as LayoutCompaniesCompanyIdIndexRouteImport } from "./pages/_layout/companies/$companyId/index"
import { Route as LayoutCompaniesCompanyIdEmployeesEmployeeIdRouteImport } from "./pages/_layout/companies/$companyId/employees/$employeeId"

const MainLayoutRoute = MainLayoutRouteImport.update({
  id: "/_main-layout",
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: "/_layout",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: "/_auth",
  getParentRoute: () => rootRouteImport,
} as any)
const MainLayoutIndexRoute = MainLayoutIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => MainLayoutRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => AuthRoute,
} as any)
const LayoutCompaniesCompanyIdIndexRoute =
  LayoutCompaniesCompanyIdIndexRouteImport.update({
    id: "/companies/$companyId/",
    path: "/companies/$companyId/",
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutCompaniesCompanyIdEmployeesEmployeeIdRoute =
  LayoutCompaniesCompanyIdEmployeesEmployeeIdRouteImport.update({
    id: "/companies/$companyId/employees/$employeeId",
    path: "/companies/$companyId/employees/$employeeId",
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/login": typeof AuthLoginRoute
  "/": typeof MainLayoutIndexRoute
  "/companies/$companyId": typeof LayoutCompaniesCompanyIdIndexRoute
  "/companies/$companyId/employees/$employeeId": typeof LayoutCompaniesCompanyIdEmployeesEmployeeIdRoute
}
export interface FileRoutesByTo {
  "/login": typeof AuthLoginRoute
  "/": typeof MainLayoutIndexRoute
  "/companies/$companyId": typeof LayoutCompaniesCompanyIdIndexRoute
  "/companies/$companyId/employees/$employeeId": typeof LayoutCompaniesCompanyIdEmployeesEmployeeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/_auth": typeof AuthRouteWithChildren
  "/_layout": typeof LayoutRouteWithChildren
  "/_main-layout": typeof MainLayoutRouteWithChildren
  "/_auth/login": typeof AuthLoginRoute
  "/_main-layout/": typeof MainLayoutIndexRoute
  "/_layout/companies/$companyId/": typeof LayoutCompaniesCompanyIdIndexRoute
  "/_layout/companies/$companyId/employees/$employeeId": typeof LayoutCompaniesCompanyIdEmployeesEmployeeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/login"
    | "/"
    | "/companies/$companyId"
    | "/companies/$companyId/employees/$employeeId"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/login"
    | "/"
    | "/companies/$companyId"
    | "/companies/$companyId/employees/$employeeId"
  id:
    | "__root__"
    | "/_auth"
    | "/_layout"
    | "/_main-layout"
    | "/_auth/login"
    | "/_main-layout/"
    | "/_layout/companies/$companyId/"
    | "/_layout/companies/$companyId/employees/$employeeId"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LayoutRoute: typeof LayoutRouteWithChildren
  MainLayoutRoute: typeof MainLayoutRouteWithChildren
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_main-layout": {
      id: "/_main-layout"
      path: ""
      fullPath: ""
      preLoaderRoute: typeof MainLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_layout": {
      id: "/_layout"
      path: ""
      fullPath: ""
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_auth": {
      id: "/_auth"
      path: ""
      fullPath: ""
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_main-layout/": {
      id: "/_main-layout/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof MainLayoutIndexRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    "/_auth/login": {
      id: "/_auth/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    "/_layout/companies/$companyId/": {
      id: "/_layout/companies/$companyId/"
      path: "/companies/$companyId"
      fullPath: "/companies/$companyId"
      preLoaderRoute: typeof LayoutCompaniesCompanyIdIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    "/_layout/companies/$companyId/employees/$employeeId": {
      id: "/_layout/companies/$companyId/employees/$employeeId"
      path: "/companies/$companyId/employees/$employeeId"
      fullPath: "/companies/$companyId/employees/$employeeId"
      preLoaderRoute: typeof LayoutCompaniesCompanyIdEmployeesEmployeeIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface LayoutRouteChildren {
  LayoutCompaniesCompanyIdIndexRoute: typeof LayoutCompaniesCompanyIdIndexRoute
  LayoutCompaniesCompanyIdEmployeesEmployeeIdRoute: typeof LayoutCompaniesCompanyIdEmployeesEmployeeIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutCompaniesCompanyIdIndexRoute: LayoutCompaniesCompanyIdIndexRoute,
  LayoutCompaniesCompanyIdEmployeesEmployeeIdRoute:
    LayoutCompaniesCompanyIdEmployeesEmployeeIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface MainLayoutRouteChildren {
  MainLayoutIndexRoute: typeof MainLayoutIndexRoute
}

const MainLayoutRouteChildren: MainLayoutRouteChildren = {
  MainLayoutIndexRoute: MainLayoutIndexRoute,
}

const MainLayoutRouteWithChildren = MainLayoutRoute._addFileChildren(
  MainLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LayoutRoute: LayoutRouteWithChildren,
  MainLayoutRoute: MainLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
